name: jikan_api
version: 1.5.0
description: Dart wrapper for the Jikan API, an unofficial MyAnimeList API.
homepage: https://github.com/javoeria/jikan-dart

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.2
  built_value: ^7.1.0
  built_collection: ^4.3.2

dev_dependencies:
  build_runner: ^1.10.2
  built_value_generator: ^7.1.0
  test: ^1.15.7
